@echo off
rem start "" /MAX "C:\Users\Public\Desktop\VMQuickConfig"
rem python -c "import pyautogui as pag; pag.click(143, 487, duration=5)"
rem python -c "import pyautogui as pag; pag.click(155, 554, duration=2)"
rem python -c "import pyautogui as pag; pag.click(637, 417, duration=2)"
rem python -c "import pyautogui as pag; pag.click(588, 10, duration=2)"
echo ..........................................................
echo .....Brought By The Disala................................
echo ..........................................................
echo ......#####...######...####....####...##.......####.......
echo ......##..##....##....##......##..##..##......##..##......
echo ......##..##....##.....####...######..##......######......
echo ......##..##....##........##..##..##..##......##..##......
echo ......#####...######...####...##..##..######..##..##......
echo ..........................................................
echo ..Youtube Video Tutorial - https://youtu.be/xqpCQCJXKxU ..
echo ..........................................................
echo User name : runneradmin
echo User Pass : TheDisa1a
echo Iperius Remote Pass : TheDisa1a

